### PR TITLE
make notice dismissible in WP 4.2

### PR DESCRIPTION
**Pull request by afragen**
Should solve #22

### CODE REVIEW

**Comment by afragen** [comment]
Not persistent though.

**Comment by coenjacobs** [comment]
Yeah, as @pderksen also mentioned:

> Is there a built-in way to make a dismiss action persistent though? Like a hide/dismiss forever sort of thing? That's where I've elected to save a setting for this in some of my plugins.

We need a way to make this persist. I like the simplicity of the new class we can add to the admin notices, but if it isn't persistent, it's not good enough for now. My gut tells me that this shouldn't be too hard though and that WordPress core probably provides a way to hook into the dismiss action?

**Comment by afragen** [comment]
It would seem that perhaps some JS to set a boolean transient and if false display the message. Set the transient to timeout for whatever period you want.

Somehow hook  to current (4.2) dismissal.

In the meantime, merging this has no downside.

**Comment by coenjacobs** [comment]
Will review this in #22. Requires more code and gonna be part of the long term plan of the library.

**Pull request closed without merging**
