### PR TITLE
add class_exists check before loading class

### PR DESCRIPTION
**Pull request by afragen**

### CODE REVIEW

**Comment by coenjacobs** [comment]
This is already in place via [your commit](https://github.com/WPupdatePHP/wp-update-php/commit/dae3eb5bfe0db60b9423b8dd9ea94e14364b54d9) that I've cherry-picked onto the the 1.1.0 release branch.

**Comment by afragen** [comment]
It's done a little differently here and it seems more in line with how others wrap the entire class in the conditional.

**Comment by coenjacobs** [comment]
It does the exact same thing though.

**Comment by afragen** [comment]
I know 😉

It's just that most other code I've seen doesn't exit a class declaration in this manner.

**Pull request closed without merging**
