### PR TITLE
Plugin name patch2

### PR DESCRIPTION
**Pull request by afragen**
1. defines generic "this plugin" in constructor so it's available to admin notices.
2. refactor admin notices for more i18n ease of translation.

Suggested use.

``` php
$updaterPhp = new WPUpdatePhp( '5.4.0' );
$updaterPhp->set_plugin_name( 'My Great Plugin' );
if ( $updatePhp->does_it_meet_required_php_version() ) {
    // Instantiate new object here
}
```

Also works correctly without the `set_plugin_name`.

### CODE REVIEW

**Comment by coenjacobs** [comment]
Hmmm. I'm note sure how I feel about this one. I actually like the fact that I have two separate strings for each version number to check for, totalling in four strings. There are languages that use different sentence structures, where we just can't plop in the 'this plugin' string which is separately translated.

I'd rather discuss the technicalities of the translating itself (as I think this is complicated to at all) in #8, before we dive in and change all the strings around.

**Comment by afragen** [comment]
If you think of it as just being the same as having the plugin's name being translated it probably works out the same. Consider the abstract case where the plugin name was actually 'This Plugin'. It's really just a substitute for the user who doesn't define the name of their plugin.

**Comment by afragen** [comment]
If you'd like I'll rewrite it with the separate strings. I was just going for efficiency.

**Comment by afragen** [comment]
FWIW, I have this pattern in the GitHub Updater plugin and my translators haven't really complained.

**Comment by coenjacobs** [comment]
I understand what you mean and I agree up to a certain level. Perhaps it's just a personal preference that I want to keep the strings separate.

**Comment by afragen** [comment]
I definitely understand re: personal prefs. I'll have another crack at it.

**Pull request closed without merging**
