### PR TITLE
update admin notice for translation and include

### PR DESCRIPTION
**Pull request by afragen**
variable for plugin name. This in anticipation on injecting plugin name to admin notice at some point.

### CODE REVIEW

**Comment by coenjacobs** [comment]
Yes, this is the right way to do this if you add a public method to set the plugin name. This needs to be made compatible with the changes on the `release-1-1-0` branch as well, but I'll take care of that when I merge this in manually. Still no idea how I'd do the text translation part of it all, but I guess I can look at that once the plugin name is in place.

**Comment by afragen** [comment]
@coenjacobs do you want me to make these PRs against a different branch?

 I've always thought release branches were like tags, essentially frozen at a point. I usually use a develop branch but you don't have one here and it seems like a lot of extra work for you the keep cherry picking.

I have another PR in mind and don't want to make it more complicated.

**Comment by coenjacobs** [comment]
Yes, if you could target new PRs to the `release-1-1-0` branch, that would be great.

**Comment by afragen** [comment]
Will do.

**Comment by afragen** [comment]
I'll fix this one too. At least until we figure out what to do about the text domain this should be a good starting point.

**Pull request closed without merging**
